### ISSUE TITLE
Course detail page

### ISSUE THREAD

**Issue by jtreanor** [jtreanor/SummerCourses#16]
Make course detail page conform to requirements.

**Comment by bao-qian** [comment]
To do:
- [x] gallery
- [x] thumbnail of media
- [x] maps

https://github.com/apneadiving/Google-Maps-for-Rails
- [x] calendar(week)

https://gist.github.com/brennovich/2582439

http://arshaw.com/fullcalendar/

https://github.com/bokmann/rails3_fullcalendar
- [x] beautify the page

**Comment by jtreanor** [comment]
The gallery isn't working on Heroku because of this error: "File to import not found or unreadable: gallery/galleria/classic."

As a consequence the whole site is down. Is it working locally for you?

**Comment by bao-qian** [comment]
Yes, it's work locally. I will figure that out.

**Comment by jtreanor** [comment]
It may be related to the precompile that occurs in production.

**Comment by bao-qian** [comment]
The whole site is working now, but the gallery still not working.

**Comment by jtreanor** [comment]
Great stuf thanks.

**Comment by bao-qian** [comment]
Do you know why ![this link](https://summercourses.herokuapp.com/assets/galleria.classic.min.js) not working,
but ![this link](https://summercourses.herokuapp.com/assets/application.js) working?

**Comment by bao-qian** [comment]
Fixed on commit ab2ce4cc5a
https://summercourses.herokuapp.com/courses/1 is working.
both picture and video is working.

**Comment by bao-qian** [comment]
Basic Google maps support is done through 
b34a471b9b6d40f53d19966762e59bde9a6eacac 
and 
99a0293819edfee8121b7ad099525b480047a180

**Comment by bao-qian** [comment]
The whole functionality is done via cadd5dac380a0e209c5a2552fbc42ec9e6274c0c.
@jtreanor , do you have any suggestion for the layout?

**Comment by jtreanor** [comment]
Perhaps only show one element at a time. Tabs could be provided for map, schedule and details. I have done something similar here: https://summercourses.herokuapp.com/enrollments/new/course/1

**Comment by bao-qian** [comment]
Nice idea, thank you.

**Comment by bao-qian** [comment]
Things to be done:
- [x] teacher tab
- [ ] JavaScript disable
- [x] full description

**Comment by bao-qian** [comment]
Done after 51efc266ecd5058294a18b0fe2b43c4568aafee3

**Comment by jtreanor** [comment]
Where is the galleria? It is not appearing for me. Perhaps it should be above the tabs?

**Comment by bao-qian** [comment]
If you add a course asset, it will appear. The teacher picture also need
add asset.

**Comment by jtreanor** [comment]
Excellent. Do you want to add activeadmin support for teachers or will I?

**Comment by bao-qian** [comment]
I can do that today.

**Comment by bao-qian** [comment]
Basically done after e92af5f26120aecace3fbaa10af5e8920d5ad68e

**Comment by jtreanor** [comment]
Adding a teacher is broken:

Mysql2::Error: Column 'description' cannot be null: INSERT INTO `assets` (`asset_content_type`, `asset_file_name`, `asset_file_size`, `asset_updated_at`, `description`) VALUES ('image/png', 'schema_final.png', 512178, '2013-03-22 10:50:52', NULL)

**Comment by bao-qian** [comment]
I forget run rake db:reset. I change the schema, because I think teacher
picture do not need description.

**Comment by jtreanor** [comment]
Okay. Thats working now.
