### ISSUE TITLE
Fix position of footer

### ISSUE THREAD

**Issue by jtreanor** [jtreanor/SummerCourses#25]

**Comment by jtreanor** [comment]
Why is this issue closed? The footer is still left aligned.
It may be useful to compare [the mockup](http://cs1.ucc.ie/~jct1/mockup) with [summercourses.herokuapp.com](https://summercourses.herokuapp.com/)
The footer is very differently aligned and the nav bar is offset to the left. The two layouts were identical yesterday with working flash messages. I understand the need to fix the responsive layout but can you explain why the other changes were made?

**Comment by bao-qian** [comment]
Sorry, it's a mistake. I want to fix the issue related to the flash message.

**Comment by jtreanor** [comment]
No problem.

**Comment by bao-qian** [comment]
Which changes do you want to explain?

**Comment by jtreanor** [comment]
jtreanor/SummerCourses@e30074802efe492056d62c119f422f52c680b9b4 and I'm not sure in what commit but the disappearance of flash messages.
