### ISSUE TITLE
UCC-logo@2x.png doesn't work

### ISSUE THREAD

**Issue by bao-qian** [jtreanor/SummerCourses#31]
It seems like every page(heroku) has this problem
![bug2](https://f.cloud.github.com/assets/1169912/209352/077c1ea8-8268-11e2-98a9-1bbc3d14bc0b.png)
![bug1](https://f.cloud.github.com/assets/1169912/209351/0774266c-8268-11e2-8c80-ad6738aeba38.png)

But on development environment(local machin), it works.

**Comment by jtreanor** [comment]
Yes I noticed this. I will look into it.

**Comment by jtreanor** [comment]
This may be useful: http://37signals.com/svn/posts/3271-easy-retina-ready-images-using-scss
