### ISSUE TITLE
Things need to be done on backend

### ISSUE THREAD

**Issue by bao-qian** [jtreanor/SummerCourses#51]
@jtreanor I add "Teacher" permission to AdminPermission through c70d8f8081773383070e90f6e7fef322a8e43f63, so it can let teacher loggin to active_admin
- [x] We lack authorization for active_admin menu, and action
- [ ] Choose picture from existing picture
- [x] Friendly error message 

~~\- [ ] The content of message thread view page needs paginate?~~

**Comment by jtreanor** [comment]
1. What do you mean by "We lack authorization for active_admin menu, and action"
2. This will work (see course form): `ca.inputs "Existing Asset" do
   ca.input :asset
   end`
3. What do you mean by "Friendly error message"? Can you give examples?
4. I am not sure pagination is necessary in MessageThread#show. The reply box is after the last message so it may be confusing for administrators.

**Comment by bao-qian** [comment]
1. for example, teacher only can see Course menu, and view action on active_admin. We only done authorization for AdminUser menu.
2. I will test it again later, because it seems not work yesterday.
3. for example, if I add new  course without input any infomation, it will give a page like this:
   ![error](https://f.cloud.github.com/assets/1169912/290597/0bc17986-92e9-11e2-96ee-6689b0359977.png)
4. Yeah, you are right.

**Comment by bao-qian** [comment]
1. It seems not working, there are no asset appear on course_asset if I create course with existing asst
   ![create_course_with_asset](https://f.cloud.github.com/assets/1169912/291849/c298bf20-9311-11e2-8c81-35660f0f05c7.png)
   ![course_asset](https://f.cloud.github.com/assets/1169912/291851/ca4a2736-9311-11e2-9cb6-c5f9af209267.png)

**Comment by bao-qian** [comment]
One more question. could you explain the relationship between this code and this button?

``` ruby
if f.object.new_record?
      f.inputs "Assets" do
        f.has_many :course_assets do |ca|
          ca.inputs "Existing Asset" do
            ca.input :asset
          end
          ca.inputs "New Asset", :for => [:asset, Asset.new ] do |fm|
              fm.input :description
              fm.input :asset, :as => :file
          end
        end
      end
    else
```

![new_course_asset](https://f.cloud.github.com/assets/1169912/291862/4817d7da-9312-11e2-9cce-b9e870e5d723.png)

**Comment by jtreanor** [comment]
Using existing assets was working previously. I'll check it out. That button allows more than one asset to be added to a course. It is generated by using f.has_many :course_assets.

**Comment by bao-qian** [comment]
Thanks

**Comment by jtreanor** [comment]
Using existing assets works when I remove the new asset option. I'm working on a way around this. In the mean time make sure you have `form :html => {:multipart => true} do |f|` at the start of your form

**Comment by jtreanor** [comment]
The only thing left here is existing images/videos.

**Comment by bao-qian** [comment]
Hi, we don't have enrolments tab on active admin?

**Comment by jtreanor** [comment]
We don't need this. Enrolments in a course can be viewed from the course show page.
