### ISSUE TITLE
Galleria bug

### ISSUE THREAD

**Issue by jtreanor** [jtreanor/SummerCourses#54]
I can't quite find the cause of this. This appears over galleria occasionally. I think it is related to switching tabs.

![Screen Shot 2013-03-25 at 12 15 05](https://f.cloud.github.com/assets/1773641/297745/be581240-9545-11e2-9fdb-39544acbc7a2.png)

**Comment by bao-qian** [comment]
Thanks, I will fix this.
Do you know some way to force reload css via javascript/jquery?

**Comment by jtreanor** [comment]
I don't. Why do you need to do this?

**Comment by bao-qian** [comment]
Because the bug is because galleria can't find height definition.

**Comment by jtreanor** [comment]
Where is this defined?
